data = '''
@_OliviaBlake.txt
@_RobbieMoore.txt
@AylesburyTories.txt
@baynes_simon.txt
@bhatti_saqib.txt
@BillCashMP.txt
@BlaenauGwentMP.txt
@BrineMP.txt
@Dunne4Ludlow.txt
@eastantrimmp.txt
@Gibbo4Darlo.txt
@GradySNP.txt
@halfon4harlowMP.txt
@HuddlestonNigel.txt
@LabourSJ.txt
@Metcalfe_SBET.txt
@morton_wendy.txt
@neill_bob.txt
@NickTorfaen.txt
@Nicola4WBE.txt
@nigelmills.txt
@OliverDowden.txt
@OliverHealdUK.txt
@OrfhlaithBegley.txt
@OwenThompson.txt
@patmcfaddenmp.txt
@PaulaBarkerMP.txt
@PaulBlomfieldMP.txt
@paulbristow79.txt
@PaulHowellMP.txt
@Pauline_Latham.txt
@pauljholmes.txt
@PaulMaskeyMP.txt
@PaulMaynardUK.txt
@PBottomleyMP.txt
@PennyMordaunt.txt
@peter_aldous.txt
@Peter_Dowd.txt
@PeterBoneUK.txt
@PeterGrantMP.txt
@peterkyle.txt
@PeteWishart.txt
@PGibsonSNP.txt
@PhilipDaviesUK.txt
@pow_rebecca.txt
@PreetKGillMP.txt
@pritipatel.txt
@Q66Suzi.txt
@rach_hopkins.txt
@RachaelMaskell.txt
@RachelReevesMP.txt
@RebeccaHarrisMP.txt
@redditchrachel.txt
@Rehman_Chishti.txt
@RichardBurgon.txt
@RichardGrahamUK.txt
@RicHolden.txt
@RishiSunak.txt
@RLong_Bailey.txt
@RobertBuckland.txt
@robertcourts.txt
@RobertJenrick.txt
@robertlargan.txt
@RobertSyms.txt
@RobinMillarMP.txt
@ronniecowan.txt
@RosieDuffield1.txt
@Royston_Smith.txt
@RThomsonMP.txt
@rushanaraali.txt
@RuthCadbury.txt
@RuthNewportWest.txt
@S_Hammond.txt
@sajidjavid.txt
@SallyAnn1066.txt
@SamTarry.txt
@SarahChampionMP.txt
@sarahjolney1.txt
@SarahOwen_.txt
@SarBritcliffeMP.txt
@ScottBentonMP.txt
@scottmann4NC.txt
@SCrabbPembs.txt
@scullyp.txt
@SDoughtyMP.txt
@SeemaMalhotra1.txt
@SelaineSaxby.txt
@ShabanaMahmood.txt
@ShaileshVara.txt
@SharonHodgsonMP.txt
@Shaun4WBW.txt
@sheryllmurray.txt
@Simon4NDorset.txt
@SimonClarkeMP.txt
@simonfell.txt
@Simonhartmp.txt
@simonjamesjupp.txt
@Siobhain_Mc.txt
@Siobhan_Baillie.txt
@SirRogerGale.txt
@SKinnock.txt
@stellacreasy.txt
@Steph_Peacock.txt
@stephenctimms.txt
@StephenFarryMP.txt
@StephenFlynnSNP.txt
@StephenMorganMP.txt
@steve_mccabe.txt
@SteveBakerHW.txt
@SteveBarclay.txt
@stevedouble.txt
@StevenBonnarSNP.txt
@SteveReedMP.txt
@StewartMcDonald.txt
@Stuart4WolvesSW.txt
@Stuart_McDonald.txt
@StuartAndrew.txt
@SuellaBraverman.txt
@TahirAliMP.txt
@TaiwoOwatemi.txt
@TanDhesi.txt
@ThangamMP.txt
@theodoraclarke.txt
@theresa_may.txt
@timfarron.txt
@timloughton.txt
@tobyperkinsmp.txt
@Tom_Randall.txt
@tomhunt1988.txt
@TommySheppard.txt
@TomTugendhat.txt
@ToniaAntoniazzi.txt
@tony4rochdale.txt
@tracey_crouch.txt
@TracyBrabin.txt
@TulipSiddiq.txt
@twocitiesnickie.txt
@Valerie_VazMP.txt
@vickyford.txt
@vickyfoxcroft.txt
@VictoriaPrentis.txt
@VirendraSharma.txt
@VotePursglove.txt
@WalkerWorcester.txt
@WayneDavid_MP.txt
@wendychambLD.txt
@Wera_Hobhouse.txt
@wesstreeting.txt
@William_Wragg.txt
@willquince.txt
@Y_FovargueMP.txt
@YasminQureshiMP.txt
@YvetteCooperMP.txt
@zarahsultana.txt
'''

print(len(data.split('\n')))
